# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Inserir_Fotografies
                                 A QGIS plugin
 Aquest plugin serveix per a inserir fotografies
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-05-16
        copyright            : (C) 2025 by Arnau Solà Tatjé
        email                : becari.a.sola@icgc.cat
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Inserir_Fotografies class from file Inserir_Fotografies.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .add_photo import Inserir_Fotografies
    return Inserir_Fotografies(iface)
